Dockerfile-indexer
Merging rp-indexer Dockerfile.
=> Ist develop

.circleci/config.yml
This corrects the project label for deployments
=> Fix the deploy project label

.env, docker-compose.yml
Adjusts mailroom config issues in the sample env and compose files - specifically the port, and matches the rapidpro redis DB with mailroom's.
=> Adjust sample compose config issues

requirements.txt, settings-engage.py, settings-generic.py, settings.py
Adjust engage to log in JSON format
=> P4-705 - Adjust engage to log in JSON format

.circleci/config.yml
=> Tag first before push

settings-engage.py, settings-generic.py, settings.py
- Added broadcast throttles to settings, so the API will work .
=> Add broadcasts throttle rate to settings

urls.py
Minor url routing fix to support 3.5 deployment
=> fix root url on non-subdir deployment

customizations/engage/templates/frame.haml
- Copied in new HAML requirements from the upstream merge in https://github.com/istresearch/rapidpro
=> Add in new HAML requirements for upstream merge

settings-engage.py, settings-generic.py, settings.py
adding missing channel types required for postmaster. https://github.com/istresearch/rapidpro/pull/67
=> Postmaster channel patch 1

settings-engage.py, settings-generic.py, settings.py
=> P4-1482 - Enable PM channel

settings-engage.py, settings-generic.py, settings.py
Updated settings to match Postmaster changes in engage P4-1355
Updated settings to match Postmaster changes in engage P4-1355
N/A
=> Updated settings to match Postmaster changes in engage P4-1355

.circleci/config.yml
Description of changes.
<Concise sentence describing change>Required.
<Description for Techops of how to handle changes, migrations, updates>None.
*Steps to test your application for someone not familiar with it.* Required.
1. Do this: `$ run-this.sh`
2. Look for this.
3. Clean up with this command
=> Release 4.0.2

Dockerfile, Dockerfile-engage, Dockerfile-generic
Description of changes.
<Concise sentence describing change>Required.
<Description for Techops of how to handle changes, migrations, updates>None.
*Steps to test your application for someone not familiar with it.* Required.
1. Do this: `$ run-this.sh`
2. Look for this.
3. Clean up with this command
=> P4-1854 - Error code when uploading contacts: Task P4-T296

Dockerfile, Dockerfile-engage, Dockerfile-generic
Reverts istresearch/rapidpro-docker#72
=> Revert "P4-1854 - Error code when uploading contacts: Task P4-T296"

settings-engage.py, settings-generic.py, settings.py
Added support for Viber and Line postmaster modes
Line and Viber postmaster modes can now be registered.
None.
See https://github.com/istresearch/rapidpro/pull/121
=> P4-1815, P4-1816 - Viber and Line modes for Postmaster

settings-engage.py, settings-generic.py, settings.py
Added new postmaster twitter mode
Added a new postmaster twitter mode
None.
See https://github.com/istresearch/rapidpro/pull/122
=> P4-1885 - Add twitter mode for PM channel

settings-engage.py, settings-generic.py, settings.py
Companion PR for https://github.com/istresearch/rapidpro/pull/126
adding default courier_url value
<Concise sentence describing change>Required.
<Description for Techops of how to handle changes, migrations, updates>None.
Companion PR
=> P4-1963 - Engage/Courier channel purge/kill switch - default settings

customizations/engage/templates/frame.haml, customizations/generic/templates/frame.haml, docker-compose.yml, urls.py
Description of changes.
<Concise sentence describing change>Required.
<Description for Techops of how to handle changes, migrations, updates>None.
*Steps to test your application for someone not familiar with it.* Required.
1. Do this: `$ run-this.sh`
2. Look for this.
3. Clean up with this command
=> Updating docker-compose to engage 4.0.5 - to trigger circleci

Dockerfile, Dockerfile-engage, Dockerfile-generic
Fixes an issue during the build process that caused NPM to attempt module installs before the intended point in the dockerfiles. Additionally fixes permission errors on bootup caused by mixed root/engage file ownership. 
N/A 
None.
Run a build (will take many minutes)
1. `docker build -t rp --build-arg VERSION_TAG=4.0.6-dev -f Dockerfile-engage .`
2. `docker run -it rp:latest sh`
3. `ls -la /rapidpro` - all files should be …
=> Fix NPM build and permissions

requirements.txt
=> add dicttoxml for cto export task
